### ISSUE TITLE
This project seems to be dead! So I created a fork as successor ...

### ISSUE THREAD

**Issue by eisbehr-** [J-Chaniotis/external-ip#11]
Hello,

in general this is _(was)_ a nice, small module to fetch your external IP address. But it seems the project is death by now. No improvements in the past, un-commented issues and long time open pull requests. Still, beside it's very old-fashioned coding style.

**Because of this, I forked this nice basis and updated it!**

For all who want some updates and support, feel free to take a look onto the "new" old module!  
It has a bunch of new features and changes.

- https://github.com/eisbehr-/external-ip
- https://www.npmjs.com/package/ext-ip

Thanks to the previous author and all contributors for the work so far! 👍 
_If you don't want to have this post here feel free to delete this._

Thank you! :octocat:

**Comment by Berkmann18** [comment]
Does this fork fixes security vulnerabilities pointed out in #12 ?
