### ISSUE TITLE
Vulnerabilities due to dependencies

### ISSUE THREAD

**Issue by Berkmann18** [J-Chaniotis/external-ip#12]
After running a live NSP scan.
I've noticed that this package is to:
- Large gzip DoS (due to `superagent@0.18.2` which needs to be updated to v3.7+)
https://nodesecurity.io/advisories/479
- DoS extended Event loop blocking and DoS memory exhaustion (due to `qs@0.6.6` not being at least at v1.0)
https://nodesecurity.io/advisories/28
https://nodesecurity.io/advisories/29
- RE DoS (due to `mime@1.2.11` that needs to be updated to v2.0.3 and `debug@1.0.5` that needs to be updated to v3.1.0)
https://nodesecurity.io/advisories/535
https://nodesecurity.io/advisories/534

**Comment by J-Chaniotis** [comment]
Hi there, thanks for pointing that out. I will look into it and probably update all the vulnerable dependencies accordingly during the weekend!

**Comment by J-Chaniotis** [comment]
I just installed the `nsp` package and performed a scan. I get `(+) No known vulnerabilities found`.
Probably you are not using the latest version (1.3.1). I am guessing that, because `superagent` was replaced with `simple-get`.

**Comment by Berkmann18** [comment]
Well, even after doing a `npm i externalip@latest --save` it still install v1.0.2 which is the latest version of this package according to https://www.npmjs.com/package/externalip.
So if you publish [v1.3.1](https://github.com/J-Chaniotis/external-ip/releases/tag/v1.3.1) to NPM that should resolve this issue.

**Comment by J-Chaniotis** [comment]
I get it now! the package name is `external-ip` with a dash. By omitting the dash, you are installing a different package. Try `npm install external-ip`  😉

**Comment by Berkmann18** [comment]
Ooh! I completely missed that out and seems to have used both interchangeably among projects :s.
At least this package doesn't have such issues.
